# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 27cb7f399d6608c0fbec09361ab40cfbe8b4326a65c9d3f8f814b1a0d4666130fe4e8e6d9a914856d1759e6792ad278c75d548164ca7faa5e450604446ba8d35

test:
  secret_key_base: 5238058f6013641f064faf2e1dd95ff5f6a639d2f81d8763f6bfe953e71185b709ce1d435cc8452d77a4874f3e8fb0dbfa044a881b3eadd4d03364e17ef94c94

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
